# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  pull_request:
    branches: [ master ]

jobs:
  build-merge:

    runs-on: ubuntu-latest

    steps:
      # Clone repo
      - name: Clone Repo
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # Setup Python
#      - name: Install Python
#        run: sudo apt-get update && sudo apt-get install -qy python

      # Setup JDK on container
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          
      - name: Install SDKMAN, Gradle Profiler and Begin Profiling
        run: |
         curl -s "https://get.sdkman.io" | bash
         source "$HOME/.sdkman/bin/sdkman-init.sh"
         sdk install gradleprofiler
         gradle-profiler --benchmark --scenario-file build_performance.scenarios --warmups 0 --iteration 1

      - uses: actions/upload-artifact@v2
        with:
         name: merge-benchmark
         path: profile-out/benchmark.csv

  build-head:
    needs: build-merge
    runs-on: ubuntu-latest

    steps:
      # Clone repo
      - name: Clone Repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
          ref: ${{ github.event.pull_request.head.sha }}

      # Setup Python
#      - name: Install Python
#        run: sudo apt-get update && sudo apt-get install -qy python

      # Setup JDK on container
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install SDKMAN, Gradle Profiler and Begin Profiling
        run: |
          curl -s "https://get.sdkman.io" | bash
          source "$HOME/.sdkman/bin/sdkman-init.sh"
          sdk install gradleprofiler
          gradle-profiler --benchmark --scenario-file build_performance.scenarios --warmups 0 --iteration 1

      - uses: actions/upload-artifact@v2
        with:
          name: head-benchmark
          path: profile-out/benchmark.csv